### ISSUE TITLE
Copyright removal

### ISSUE THREAD

**Issue by AlexALX** [umods/BGrade#1]
Hello, i'm original author of automatic build grades plugin, and i'm bit disappointing that you completely removed copyright from plugin. Please add that your plugin based on old plugin and i'm creator of it. Removing mention about original authors is always bad, even if you change plugin a lot. or did you wrote it from scratch? Then it will be different situation. Just want to know what happens with my old plugin)

**Comment by lukespragg** [comment]
Hi @alexalx, it looks like that got overlooked when I added the reader for the plugin. I add it to all plugin readme files that are versions of or based on the original version of a plugin generally. What was the original header inside of the plugin? I’m mobile right now,  it will check either way when I get home.

**Comment by AlexALX** [comment]
Last version of copyright was:

```/*
	Created By AlexALX (c) 2015-2017
	Special thanks to: recon, freaky
	for keep plugin work with latest rust updates
*/
```

Of course you can add yourself as successor and other people to this list too. And please put my nickname to Info array for example as "AlexALX / Ryan". Thank you.

**Comment by Ryan-J-D** [comment]
I have rewrote the plugin from the bottom up.

**Comment by AlexALX** [comment]
rewrote doesn't mean wrote from scratch, so you at least should mention original author on what it was based.

**Comment by Ryan-J-D** [comment]
I have rewritten it from scratch. There is no source of your original plugin in this plugin.

I have also renamed the plugin.

**Comment by AlexALX** [comment]
Ok i compared coded and yeah, it looks different, then sorry for bothering you guys. Take care of this plugin)
